import 'ui/src/style/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
	title: 'Create Turborepo',
	description: 'Generated by create turbo',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}): JSX.Element {
	return (
		<html lang="en">
			<body className={clsx(inter.variable, 'font-sans')}>{children}</body>
		</html>
	)
}
